import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { sendEmail } from "@/lib/email";
import { emailLayout, escapeHtml } from "@/lib/email-html";

const schema=z.object({certificateId:z.string().min(8).max(80)});
export async function POST(request:Request){const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"A valid certificate ID is required."},{status:400});const supabase=await createClient();if(!supabase)return NextResponse.json({error:"Supabase is unavailable."},{status:503});const{data:{user}}=await supabase.auth.getUser();if(!user||!["admin","staff"].includes(user.app_metadata?.role))return NextResponse.json({error:"Staff access required."},{status:403});const{data,error}=await supabase.from("certificates").select("certificate_number,status,registration_id,session_id,registration:registrations(full_name,email),session:sessions(title)").eq("certificate_number",parsed.data.certificateId).eq("status","issued").single();if(error||!data)return NextResponse.json({error:"Issued certificate not found."},{status:404});const{data:attendance}=await supabase.from("attendance").select("status").eq("registration_id",data.registration_id).eq("session_id",data.session_id).eq("status","present").maybeSingle();if(!attendance)return NextResponse.json({error:"Certificate can only be sent to participants marked present in this session."},{status:400});const registration=Array.isArray(data.registration)?data.registration[0]:data.registration;const session=Array.isArray(data.session)?data.session[0]:data.session;if(!registration?.email)return NextResponse.json({error:"Participant email is unavailable."},{status:409});const origin=process.env.NEXT_PUBLIC_SITE_URL??new URL(request.url).origin;const certificateUrl=`${origin}/api/certificates/${encodeURIComponent(data.certificate_number)}`;const verifyUrl=`${origin}/verify/${encodeURIComponent(data.certificate_number)}`;const delivery=await sendEmail({to:registration.email,toName:registration.full_name,subject:`Your certificate: ${session?.title??"Deepfakes and Digital Trust"}`,tags:["certificate-notification"],html:emailLayout("Your certificate is ready",`<p>Hello ${escapeHtml(registration.full_name)},</p><p>Your attendance has been verified for <strong>${escapeHtml(session?.title??"the webinar session")}</strong>.</p><p><a href="${certificateUrl}" style="display:inline-block;background:#cf4c10;color:#fff;text-decoration:none;padding:13px 18px;font-weight:700">Download certificate</a></p><p style="font-size:13px">Public verification: <a href="${verifyUrl}">${verifyUrl}</a></p>`)});if(!delivery.delivered)return NextResponse.json({error:delivery.reason},{status:502});await supabase.from("audit_logs").insert({user_id:user.id,action:"certificate.email_sent",entity_type:"certificate",entity_id:data.certificate_number,metadata:{recipient:registration.email,message_id:delivery.id}});return NextResponse.json({sent:true,messageId:delivery.id})}

