import { CalendarDays, CheckCircle2, ShieldCheck } from "lucide-react";
import { EVENT } from "@/lib/event";
import RegistrationForm from "@/components/registration-form";
import MotionIntro from "@/components/motion-intro";

export default function HomePage() {
  return <main><MotionIntro />
    <header className="site-header shell"><a className="wordmark" href="#top" aria-label="Deepfakes and Digital Trust home">DDT / 2026</a><nav aria-label="Primary navigation"><a href="#sessions">Sessions</a><a href="#register">Registration</a><a href="/my-registration">My Registration</a><a href="/verify">Verify certificate</a></nav></header>
    <section id="top" className="hero shell" aria-labelledby="event-title"><div className="hero-copy reveal"><div className="metadata-row" aria-label="Event metadata"><span>EVENT / 001</span><span>DATE / {EVENT.isoDate}</span><span>STATUS / REGISTRATION OPEN</span></div><h1 id="event-title">Deepfakes<br /><span>&amp; Digital Trust</span></h1><p className="hero-subtitle">Recognizing AI-Generated Media and Misinformation</p><p className="hero-description">Join us to learn how to identify manipulated AI-generated media and verify online information.</p><div className="hero-actions"><a className="button button-primary" href="#register">Register for {EVENT.date}</a><a className="text-link" href="#sessions">Compare the two sessions</a></div></div>
      <div className="signal-visual reveal" role="img" aria-label="Abstract media verification interface placeholder"><div className="visual-top"><span>MEDIA / ANALYSIS</span><span>FRAME 1842</span></div><div className="face-field"><div className="scan-line" /><div className="target target-a" /><div className="target target-b" /><span className="visual-placeholder">Replaceable event visual</span></div><div className="visual-readout"><span>SIGNAL</span><strong>VERIFY SOURCE</strong><span>01:00:24</span></div></div>
    </section>
    <section className="event-strip" aria-label="Event essentials"><div className="shell essentials"><div><CalendarDays aria-hidden="true" /><span>Sunday</span><strong>{EVENT.date}</strong></div><div><ShieldCheck aria-hidden="true" /><span>Format</span><strong>Live online webinar</strong></div><div><CheckCircle2 aria-hidden="true" /><span>Certificates</span><strong>One per attended session</strong></div></div></section>
    <section id="sessions" className="sessions shell" aria-labelledby="sessions-title"><div className="section-heading reveal"><span className="section-index">01 / PROGRAM</span><h2 id="sessions-title">Choose the track that fits your context.</h2><p><strong>Note:</strong> Session 1 and Session 2 cover different topics. You may register for one or both sessions.</p></div><div className="session-list">{EVENT.sessions.map((session, index) => <article className="session-row reveal" key={session.key}><span className="session-number">{session.number}</span><div><span className="technical-label">SESSION / {session.number}</span><h3>{session.title}</h3><p>{session.description}</p></div><div className="session-time"><span>{index === 0 ? "08:00" : "14:00"}</span><i aria-hidden="true" /><span>{index === 0 ? "13:00" : "19:00"}</span><small>Asia / Manila</small></div></article>)}</div><p className="certificate-note">Separate e-certificates will be provided for each session attended.</p></section>
    <section id="register" className="registration-section" aria-labelledby="registration-title"><div className="shell registration-layout"><aside className="registration-context reveal"><span className="section-index">02 / REGISTRATION</span><h2 id="registration-title">Register for the Webinar</h2><p>Reserve your place, choose either session or both, and enter your certificate name exactly as it should appear.</p><dl><div><dt>Event date</dt><dd>{EVENT.date}</dd></div><div><dt>Delivery</dt><dd>The Google Meet link will be sent to your email</dd></div><div><dt>Certificate</dt><dd>Issued after verified attendance</dd></div></dl><p className="privacy-summary"><ShieldCheck aria-hidden="true" /> Your information is used only for registration, attendance tracking, event communication, and certificate issuance.</p></aside><RegistrationForm /></div></section>
    <footer className="site-footer shell"><div><strong>Deepfakes &amp; Digital Trust</strong><span>Recognition begins with verification.</span></div><div><a href="/verify">Verify a certificate</a><a href="/admin">Staff portal</a></div><span>EVENT / 001 · 2026</span></footer>
  </main>;
}

