import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendEmail } from "@/lib/email";
import { emailLayout, escapeHtml } from "@/lib/email-html";

const schema=z.object({audience:z.enum(["all","session-1","session-2"]),subject:z.string().trim().min(3).max(140),message:z.string().trim().min(3).max(3000),link:z.string().url().max(500)});
export async function POST(request:Request){const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Check the audience, subject, message, and link."},{status:400});const supabase=await createClient();const admin=createAdminClient();if(!supabase||!admin)return NextResponse.json({error:"Email service is unavailable."},{status:503});const{data:{user}}=await supabase.auth.getUser();if(!user||!["admin","staff"].includes(user.app_metadata?.role))return NextResponse.json({error:"Staff access required."},{status:403});let query=admin.from("registrations").select("id,email,full_name,registration_sessions!inner(session:sessions!inner(slug))").is("cancelled_at",null);if(parsed.data.audience!=="all")query=query.eq("registration_sessions.sessions.slug",parsed.data.audience);const{data:people,error}=await query;if(error)return NextResponse.json({error:"Recipients could not be loaded."},{status:500});const unique=[...new Map((people??[]).map(person=>[person.email.toLowerCase(),person])).values()];let sent=0;let failed=0;for(const person of unique){const delivery=await sendEmail({to:person.email,toName:person.full_name,subject:parsed.data.subject,tags:["registrant-message",parsed.data.audience],html:emailLayout(parsed.data.subject,`<p>Hello ${escapeHtml(person.full_name)},</p><p style="white-space:pre-line">${escapeHtml(parsed.data.message)}</p><p><a href="${escapeHtml(parsed.data.link)}" style="display:inline-block;background:#cf4c10;color:#fff;text-decoration:none;padding:13px 18px;font-weight:700">Open event link</a></p><p style="font-size:12px;word-break:break-all">${escapeHtml(parsed.data.link)}</p>`)});if(delivery.delivered)sent++;else failed++}await admin.from("audit_logs").insert({user_id:user.id,action:"registrants.message_sent",entity_type:"audience",entity_id:parsed.data.audience,metadata:{subject:parsed.data.subject,sent,failed}});return NextResponse.json({sent,failed,total:unique.length})}
